site_name: "untitled site"
# repo_name: b-init/b-init.github.io
# repo_url: https://github.com/b-init/b-init.github.io
site_url: https://b-init.github.io/
copyright: '"All of my setbacks were my fault, and all of my success was dumb luck"'  

extra_css:
  - stylesheets/extra.css

nav:
  - Homepage: index.md
  - Projects:
    - nav/projects/flub60.md
  - Artsy: 
    - Finished: artsy/finished/finished.md
    - Unfinished/Concepts: artsy/concepts/concepts.md
  - Others:
    - others/about.md
  - References: nav/references.md

theme:
  name: simple-blog
  # favicon: assets/favicon.ico
  # logo: assets/logo.png
  # theme_style: light  
  site_name_style: bold
  title_style: bold
  components:
    site_name: true
    title: true
    menu: true
    preview: true
    footer: true
  # colors: custom-defined in extra.css


plugins:
  - mkdocs-video
  - glightbox